### ISSUE TITLE
Please also release a Windows binary

### ISSUE THREAD

**Issue by sschuberth** [amzn/askalono#23]
The title says it all 😉 Maybe this could be done independently of [using AppVeyor](https://github.com/amzn/askalono/issues/8) for CI?

**Comment by jpeddicord** [comment]
AppVeyor is actually [enabled](https://github.com/amzn/askalono/blob/master/.appveyor.yml), however I don't currently have it automatically attaching exes to releases due to some API issues with how AppVeyor integrates with organizations. We have it set up as a "dumb" git clone instead of a GitHub integration due to some interactions that result in [overly-broad permissions to organizational resources](https://github.com/appveyor/ci/issues/1979).

Artifacts are, in the meantime, available here: https://ci.appveyor.com/project/jpeddicord/askalono-uhq7u/build/artifacts

**Comment by sschuberth** [comment]
Thanks, I'll be using the Windows binary directly from AppVeyor then meanwhile.

**Comment by sschuberth** [comment]
I see that [release 0.2.0](https://github.com/amzn/askalono/releases/tag/0.2.0) now has a Windows binary, thanks!
